import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "../components/Navbar/navbar";
import { ThemeProvider } from "@/components/theme-switch";
import Header from "@/components/header";
import { Plus_Jakarta_Sans } from "next/font/google";

const fontSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} antialiased`}>
        <ThemeProvider>
          <main className="bg-background dark:bg-foreground min-h-screen">
            <Header />
            <Navbar />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
